apiVersion: apps/v1
kind: Deployment
metadata:
  name: newnodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newnodejs
  template:
    metadata:
      labels:
        app: newnodejs
    spec:
      containers:
      - name: newnodejs-container
        image: madhu1607/newnodejs:latest  
        ports:
        - containerPort: 80
